# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: elixir:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service

variables:
  DEBUG: api
  PORT: '4001'
  MIX_ENV: test

test:
  script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix deps            # Print out for debugging
  - mix test

production:
  type: deploy
  script:
  - curl -L https://raw.githubusercontent.com/andjosh/heropush/master/heropush -o heropush && chmod +x heropush
  - HEROKU_APP=$HEROKU_PRODUCTION_APP_NAME HEROKU_API_KEY=$HEROKU_PRODUCTION_API_KEY ./heropush .
  only:
  - tags

staging:
  type: deploy
  script:
  - curl -L https://raw.githubusercontent.com/andjosh/heropush/master/heropush -o heropush && chmod +x heropush
  - HEROKU_APP=$HEROKU_STAGING_APP_NAME HEROKU_API_KEY=$HEROKU_STAGING_API_KEY ./heropush .
  only:
  - master
